changelog:
  categories:
    - title: New features
      labels:
        - feat
        - main

    - title: Bug fixes
      labels:
        - bug

    - title: New enhancements
      labels:
        - main