changelog:
  categories:
    - title: New features
      labels:
        - feat

    - title: Bug fixes
      labels:
        - bug

    - title: New enhancements
      labels:
        - enhancement
        - "tech debt"
        
    - title: Other Changes
      labels:

        - "*"
