name: Another service release (service 2)

on:
  push:
    branches: [ main ]
    paths: [ 'src/Arda.AnotherService/**' ]
  workflow_dispatch:

env:
  PROJECT_PATH: 'src/Arda.AnotherService/Arda.AnotherService.sln'
  
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 9.0.*
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        
    - name: Install dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore
      
    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }} --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --no-restore -o app/publish /p:UseAppHost=false

    - name: Publish artifact
      uses: actions/upload-artifact@v4
      with:
        name: main-app
        path: app/publish

  deploy-to-dev:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: main-app

    - name: Deploy to Dev server
      run: echo "Deploying to Dev server..."

  deploy-to-prod:
    if: github.ref == 'refs/heads/main'
    needs: deploy-to-dev
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: main-app

    - name: Deploy to Prod server
      run: echo "Deploying to Prod server..."