on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ardabada/nuget-version-action@v0.8
        with:
          major: 1
          minor: 0
          package_type: 'nuget'
          pivot_package_name: 'Arda.Utilities'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The new version is ${{ steps.hello.outputs.version }}"
