on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: ardabada/nuget-version-action@v0.5
        with:
          major: 1
          minor: 2
          patch: 3
          revision: 1222
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The new version is ${{ steps.hello.outputs.version }}"
