name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
          - development
      tag:
        description: 'Release Tag'
        required: true
        type: string

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout