name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  PROJECT_PATH: 'src/Arda.Utilities/Arda.Utilities.sln'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/ardabada/index.json'
  MAJOR: 1
  MINOR: 0
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.*
        # Authenticates packages to push to GPR
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - uses: einaregilsson/build-number@v1
      id: buildnumber
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        prefix: utils
    - name: Install dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore /p:Version=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.steps.buildnumber.outputs.build_number }} /p:AssemblyVersion=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.steps.buildnumber.outputs.build_number }} /p:FileVersion=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.steps.buildnumber.outputs.build_number }}
   # - name: Test
   #   run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release /p:Version=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.steps.buildnumber.outputs.build_number }} /p:AssemblyVersion=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.steps.buildnumber.outputs.build_number }} /p:FileVersion=${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.steps.buildnumber.outputs.build_number }} --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
    - name: PushGithub
      # The github token is automatically being pulled from the workflow
      #run: dotnet nuget push **/*.nupkg --no-symbols --skip-duplicate 
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ github.token }} -s ${{ env.NUGET_SOURCE_URL }} --skip-duplicate
