name: Integration tests

on:
  workflow_dispatch:

env:
  PROJECT_PATH: 'src/PipelineIntegrationTestSample/PipelineIntegrationTestSample.sln'
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.*
        
    - name: Install dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore
      
    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }} --no-restore --verbosity normal