# name: Auto label PRs to main

# on:
#   pull_request_target:
#     types: [opened, reopened, synchronize, edited, ready_for_review]

# permissions:
#   contents: read
#   pull-requests: write

# jobs:
#   label:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Add labels by branch rules
#         uses: actions/github-script@v7
#         with:
#           script: |
#             const pr = context.payload.pull_request;
#             const toAdd = new Set();

#             // 1) Add "main" to all PRs that go to main
#             if (pr.base.ref === 'main') {
#               toAdd.add('main');

#               // 2) Add "feat" to PRs from feat/* going to main
#               if (pr.head.ref.startsWith('feat/')) {
#                 toAdd.add('feat');
#               }
#             }

#             if (toAdd.size === 0) {
#               core.info('No labels to add for this PR.');
#               return;
#             }

#             await github.rest.issues.addLabels({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               issue_number: pr.number,
#               labels: [...toAdd]
#             });
#             core.info(`Added labels: ${[...toAdd].join(', ')}`);

#       - name: Label by changed files
#         uses: actions/labeler@v5
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#           configuration-path: .github/labeler.yml
#           sync-labels: true


name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v6
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        configuration-path: .github/labeler.yml
        sync-labels: true